parameters:
  agentPool: ''
  pythonVersion: ''
  env: ''
  mainRepositoryName: ''

jobs:
- job: Configure_Spark_Cluster
  pool:
    vmImage: ${{ parameters.agentPool }}
  steps:
  - checkout: self
    persistCredentials: false
    clean: false
  - template: ../steps/initialise-python.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}
      mainRepositoryName: ${{ parameters.mainRepositoryName }}
  - template: ../steps/build-wheel.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}
      mainRepositoryName: ${{ parameters.mainRepositoryName }}