parameters:
  agentPool: ''
  pythonVersion: ''
  env: ''
  mainRepositoryName: ARIAMigration-Databrick

jobs:
- job: Deploy_App
  pool:
    vmImage: ${{ parameters.agentPool }}
  steps:
  - checkout: self
  - template: ../steps/initialise-python.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}
      mainRepositoryName: ${{ parameters.mainRepositoryName }}
  - template: ../steps/build-wheel.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}
      mainRepositoryName: ${{ parameters.mainRepositoryName }}
