parameters:
  agentPool: ''
  pythonVersion: ''
  env: ''

jobs:
- job: Deploy_App
  pool:
    vmImage: ${{ parameters.agentPool }}
  steps:
  - template: ../steps/initialise-python.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}
  - template: ../steps/build-wheel.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}