parameters:
  agentPool: ''
  pythonVersion: ''
  env: ''

##
# Deploy the specified app
##
jobs:
- job: Deploy_App
  pool:
    vmImage: ${{ parameters.agentPool }}
  steps:
  - template: ../steps/initialise-python.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      env: ${{ parameters.env }}
      mainRepositoryName: ARIAMigration-Databrick
