parameters:
  agentPool: ''
  pythonVersion: ''
  env: ''

##
# Deploy the specified app
##
jobs:
- job: Deploy_App
  pool: ${{ parameters.agentPool }}
  steps:
  - template: pipeline/steps/initialise-python.yaml
    parameters:
      pythonVersion: 3.10
      env: ${{ parameters.env }}
      mainRepositoryName: ARIAMigration-Databrick