parameters:
- name: env
  displayName: Environment
  type: string
  default: 'sbox'
  values:
  - 'sbox'
  - 'stg'
- name: runJob
  displayName: Run Deployed Job
  type: boolean
  default: true
- name: databricksClusterId
  displayName: Databricks Cluster ID
  type: string
  default: '1121-123925-fa7rrd19'
- name: configureDBCluster
  displayName: Check for Shared Functions Update
  type: boolean
  default: false

name: ARIA Data Migration CI Pipeline - ${{ parameters.env }}
trigger:
- master

variables:
  resourceGroupName: ingest00-main-${{ parameters.env }}
  agentPool: "ubuntu-latest"

stages:
  - template: pipeline/jobs/deploy.yaml
    parameters:
      environment: sbox
      env:  ${{ parameters.env }}
      agentPool: $(agentPool)
      azureSubscriptionName: 'DTS-DATAINGEST-SBOX'
      runDeploy: eq('${{ parameters.env }}', 'sbox')
      pythonVersion: 3.10
      mainRepositoryName: 'ARIAMigration-Databrick'
      databricksInstance: 'https://adb-3635282203417052.12.azuredatabricks.net'
      databricksClusterId: ${{ parameters.databricksClusterId }}
      configureDBCluster: ${{ parameters.configureDBCluster }}
      runJob: ${{ parameters.runJob }}

  - template: pipeline/jobs/deploy.yaml
    parameters:
      environment: stg
      env: parameters.env
      agentPool: $(agentPool)
      azureSubscriptionName: "DTS-DATAINGEST-STG"
      runDeploy: eq('${{ parameters.env }}', 'stg')
      pythonVersion: 3.10
      mainRepositoryName: 'ARIAMigration-Databrick'
      databricksInstance: 'https://adb-3635282203417052.12.azuredatabricks.net'
      databricksClusterId: ${{ parameters.databricksClusterId }}
      configureDBCluster: ${{ parameters.configureDBCluster }}
      runJobs: ${{ parameters.runJob }}