trigger:
  branches:
    include:
    - main


pool:
  vmImage: 'ubuntu-latest' 

variables:
  - name: env
    value: 'sandbox'
  - name: DATABRICKS_HOST_WORKSPACE_MAIN00
    value: 'https://adb-3635282203417052.12.azuredatabricks.net'
  - name: DATABRICKS_HOST_WORKSPACE_MAIN01
    value: 'https://adb-376876256300083.3.azuredatabricks.net/'
  - name: DATABRICKS_HOST_WORKSPACE_MAIN02
    value: 'https://adb-1879076228317698.18.azuredatabricks.net'
  - name: StorageAccount
    value: 'ingest02rawsbox'

stages:
- stage: 'Build'
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Run Build and deploy'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.x'
      inputs:
        versionSpec: '3.x'

    - script: |
        python --version
        pip install --upgrade pip
        pip install build
        pip install databricks-cli
        python -m build --wheel --outdir $(Build.SourcesDirectory)/Databricks/SharedFunctionsLib/dist \
          $(Build.SourcesDirectory)/Databricks/SharedFunctionsLib

        ls -la $(Build.SourcesDirectory)/Databricks/SharedFunctionsLib/dist

      displayName: 'Install Python dependencies & build Python wheel'

    # Configure and deploy to Workspace MAIN00
    - script: |
        echo "[DEFAULT]" > $(HOME)/.databrickscfg
        echo "host = $(DATABRICKS_HOST_WORKSPACE_MAIN00)" >> $(HOME)/.databrickscfg
        echo "token = $(DATABRICKS_TOKEN_WORKSPACE_MAIN00)" >> $(HOME)/.databrickscfg
      displayName: 'Configure Databricks CLI for Workspace MAIN00'

    - script: |
        databricks workspace delete /live --recursive 
        databricks workspace mkdirs /live
        databricks workspace import_dir Databricks /live --overwrite
      displayName: 'Publish Databricks folder to /live in Databricks MAIN00 Workspace'

    # Configure and deploy to Workspace MAIN01
    - script: |
        echo "[DEFAULT]" > $(HOME)/.databrickscfg
        echo "host = $(DATABRICKS_HOST_WORKSPACE_MAIN01)" >> $(HOME)/.databrickscfg
        echo "token = $(DATABRICKS_TOKEN_WORKSPACE_MAIN01)" >> $(HOME)/.databrickscfg
      displayName: 'Configure Databricks CLI for Workspace MAIN01'

    - script: |
        databricks workspace delete /live --recursive
        databricks workspace mkdirs /live
        databricks workspace import_dir Databricks /live --overwrite
      displayName: 'Publish Databricks folder to /live in Databricks MAIN01 Workspace'

    # Configure and deploy to Workspace MAIN02
    - script: |
        echo "[DEFAULT]" > $(HOME)/.databrickscfg
        echo "host = $(DATABRICKS_HOST_WORKSPACE_MAIN02)" >> $(HOME)/.databrickscfg
        echo "token = $(DATABRICKS_TOKEN_WORKSPACE_MAIN02)" >> $(HOME)/.databrickscfg
      displayName: 'Configure Databricks CLI for Workspace MAIN02'

    - script: |
        databricks workspace delete /live --recursive
        databricks workspace mkdirs /live
        databricks workspace import_dir Databricks /live --overwrite
      displayName: 'Publish Databricks folder to /live in Databricks MAIN02 Workspace'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/Databricks/SharedFunctionsLib/dist'
        ArtifactName: 'ariafunction'
        publishLocation: 'Container'
      displayName: 'Publish Wheel Artifact'
    
- stage: 'Deploy'
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployDatabricksResources
    displayName: 'Run Build and deploy'
    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'ariafunction'
        downloadPath: '$(Pipeline.Workspace)'
      displayName: 'Download wheel Artifact'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.x'
      inputs:
        versionSpec: '3.x'

    - script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          
          brew install databricks/tap/databricks
          databricks --version
      displayName: 'Install Databricks CLI'

      #Ensure databrcks CLI is available in current session (loading homebrew shell)
    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"  
        databricks --version  
        echo "[DEFAULT]" > $(HOME)/.databrickscfg
        echo "host = $(DATABRICKS_HOST_WORKSPACE_MAIN02)" >> $(HOME)/.databrickscfg
        echo "token = $(DATABRICKS_TOKEN_WORKSPACE_MAIN02)" >> $(HOME)/.databrickscfg
        cat ~/.databrickscfg  # Print the contents for debugging
      displayName: 'Configure Databricks CLI for Workspace MAIN02'

    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"  

        set -e 

        WHEEL_FILE=$(find '$(Pipeline.Workspace)' -name "*.whl" | tail -n 1)

        if [ -n "$WHEEL_FILE" ]; then
          echo "Found wheel file: $WHEEL_FILE"

          FILENAME=$(basename "$WHEEL_FILE")
          echo "Extracted filename: $FILENAME"

          DEST_PATH="dbfs:/FileStore/shared_wheels/$FILENAME"
          echo "Destination path: $DEST_PATH"

          echo "creating directory dbfs:/FileStore/shared_wheels"
          databricks fs mkdirs dbfs:/FileStore/shared_wheels    

          echo "copying wheel file to DBFS..."
          echo "copying $WHEEL_FILE to $DEST_PATH"
          databricks fs cp "$WHEEL_FILE" "$DEST_PATH" --overwrite --debug

          echo "Displaying content of dbfs:/FileStore/shared_wheels"
          databricks fs ls dbfs:/FileStore/shared_wheels

        else
          echo "No wheel file found"
          exit 1
        fi
      displayName: 'Upload Wheel to Databricks DBFS'
    
    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" 

        echo "Assigning Databricks Scope to store secret values"
        databricks secrets delete-scope aria
        databricks secrets create-scope aria 
        echo "Successfully created scope <aria>!"

        echo "Hashing values before storing..."
        echo -n "Client_ID: $SP_CLIENT_ID" | sha256sum
        echo -n "Client_Secret: $SP_CLIENT_SECRET" | sha256sum
        echo -n "Tenant_ID: $TENANT_ID" | sha256sum
        echo -n "Tenant_URL: $TENANT_URL" | sha256sum

        echo "Assigning Databricks secret values ..."
        databricks secrets put-secret --json '{
        "scope": "aria",
        "key": "sp_client_id",
        "string_value": "$(SP_CLIENT_ID)"
        }'

        databricks secrets put-secret --json '{
        "scope": "aria",
        "key": "sp_client_secret",
        "string_value": "$(SP_CLIENT_SECRET)"
        }'

        databricks secrets put-secret --json '{
        "scope": "aria",
        "key": "sp_tenant_id",
        "string_value": "$(SP_TENANT_ID)"
        }'

        databricks secrets put-secret --json '{
        "scope": "aria",
        "key": "sp_tenant_url",
        "string_value": "$(TENANT_URL)"
        }'
        echo "Secrets assigned successfully!"

        echo "Query databricks secret scopes"
        databricks secrets list-scopes

        echo "Query databricks secrets inside aria scope"
        databricks secrets list-secrets aria

        echo "read secret values stored: tenant_url, tenant_id, client_id, client_secret"
        databricks secrets get-secret aria sp_tenant_url | jq -r .value | base64 --decode
        databricks secrets get-secret aria sp_tenant_id | jq -r .value | base64 --decode
        databricks secrets get-secret aria sp_client_id | jq -r .value | base64 --decode
        databricks secrets get-secret aria sp_client_secret | jq -r .value | base64 --decode
        
        CLIENT_ID=$(databricks secrets get-secret aria sp_client_id)
        CLIENT_SECRET=$(databricks secrets get-secret aria sp_client_secret)
        TENANT_ID=$(databricks secrets get-secret aria sp_tenant_id)

        # Exporting the values
        export CLIENT_ID
        export CLIENT_SECRET
        export TENANT_ID
      displayName: 'Push secrets to Databricks'

    - script: |
        echo "Current dir: $(pwd)"
        ls -al /home/vsts/work/1/s
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" 

        cd ARIA_DABs

        echo "Current dir: $(pwd)"
        ls -al  

        databricks bundle destroy -t sandbox 
        databricks bundle validate -t sandbox --debug
        databricks bundle deploy -t sandbox --debug

        databricks bundle run OAuth_job_v1
      displayName: "Deploy Databricks resources to ingest02 workspace"

