trigger:
  branches:
    include:
      - master   # Trigger on commits to the main branch

pool:
  vmImage: 'ubuntu-latest' 

variables:
  DATABRICKS_HOST_WORKSPACE_MAIN00: 'https://adb-3635282203417052.12.azuredatabricks.net'
  DATABRICKS_TOKEN_WORKSPACE_MAIN00: $(DATABRICKS_TOKEN_WORKSPACE_MAIN00)

  DATABRICKS_HOST_WORKSPACE_MAIN02: 'https://adb-1879076228317698.18.azuredatabricks.net'
  DATABRICKS_TOKEN_WORKSPACE_MAIN02: $(DATABRICKS_TOKEN_WORKSPACE_MAIN02)



steps:
# 1. Ensure we’re using Python 3.x
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'
  inputs:
    versionSpec: '3.x'

# 2. Install the Databricks CLI via pip
- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli
  displayName: 'Install Databricks CLI'

# 3. Configure the Databricks CLI  for main00 workspace by creating a config file (~/.databrickscfg)
- script: |
    echo "[DEFAULT]" > $(HOME)/.databrickscfg
    echo "host = $(DATABRICKS_HOST_WORKSPACE_MAIN00)" >> $(HOME)/.databrickscfg
    echo "token = $(DATABRICKS_TOKEN_WORKSPACE_MAIN00)" >> $(HOME)/.databrickscfg
  displayName: 'Configure Databricks CLI'

# 4. Import the Databricks folder from the repo into the /live folder of your Databricks workspace
- script: |
    databricks workspace delete /live --recursive 
    databricks workspace import_dir Databricks /live --overwrite
  displayName: 'Publish Databricks folder to /live in Databricks main00 Workspace'

# 5 Configure the Databricks CLI for Main02 workspace by creating config file
- script:
    echo "[DEFAULT]" > $(HOME)/.databrickscfg
    echo "host" = $(DATABRICKS_HOST_WORKSPACE_MAIN02) >> $(HOME)/.databrickscfg
    echo "token" = $(DATABRICKS_TOKEN_WORKSPACE_MAIN02) >> $(HOME)/.databrickscfg

# 6 import the databricks folder from the repo to a live folder of the main002 workspace
- script:
    databricks workspace delete /live --recursive
    databricks workspace import_dir Databricks /live --overwrite
  displayName: 'Publish Databricks folder to /live in Databricks main02 Workspace'
