parameters:
- name: configureCluster
  type: boolean
  default: false
- name: env
  displayName: Environment
  type: string
  default: 'sbox'
  values:
  - sbox
- name: databricksClusterId
  type: string
  default: ''

name: ARIA Data Migration CI Pipeline - ${{ parameters.env }}
trigger:
- master

variables:
  resourceGroupName: ingest00-main-${{ parameters.env }}
  agentPool: "ubuntu-latest"

stages:
  - stage: Configure
    displayName: ''
    jobs:
    - template: pipeline/jobs/configure.yaml
      parameters:
        agentPool: $(agentPool)
        pythonVersion: 3.10
        env: ${{ parameters.env }}
        mainRepositoryName: 'ARIAMigration-Databrick'
        databricksInstance: 'https://adb-3635282203417052.12.azuredatabricks.net'
        databricksClusterId: ${{ parameters.databricksClusterId }}