parameters:
- name: env
  displayName: Environment
  type: string
  default: 'sbox'
  values:
  - sbox
  - test
  - staging
- name: runJob
  displayName: Run Deployed Job
  type: boolean
  default: true
- name: databricksClusterId
  displayName: Databricks Cluster ID
  type: string
  default: '1121-123925-fa7rrd19'
- name: configureDBCluster
  displayName: Update Shared Functions
  type: boolean
  default: false

name: ARIA Data Migration CI Pipeline - ${{ parameters.env }}
trigger:
- master

variables:
  resourceGroupName: ingest00-main-${{ parameters.env }}
  agentPool: "ubuntu-latest"

stages:
  - template: pipeline/jobs/deploy.yaml
    parameters:
      environment: 'sbox'
      env: 'sbox'
      agentPool: $(agentPool)
      runDeploy: eq('${{ parameters.env }}', 'sbox')
      pythonVersion: 3.10
      mainRepositoryName: 'ARIAMigration-Databrick'
      databricksInstance: 'https://adb-3635282203417052.12.azuredatabricks.net'
      databricksClusterId: ${{ parameters.databricksClusterId }}
      configureDBCluster: ${{ parameters.configureDBCluster }}
      runJobs: ${{ parameters.runJob }}

  - template: pipeline/jobs/deploy.yaml
    parameters:
      environment: 'test'
      env: 'test'
      agentPool: $(agentPool)
      runDeploy: eq('${{ parameters.env }}', 'test')
      pythonVersion: 3.10
      mainRepositoryName: 'ARIAMigration-Databrick'
      databricksInstance: 'https://adb-3635282203417052.12.azuredatabricks.net'
      databricksClusterId: ${{ parameters.databricksClusterId }}
      configureDBCluster: ${{ parameters.configureDBCluster }}
      runJobs: ${{ parameters.runJob }}