parameters:
- name: configureCluster
  type: boolean
  default: true
- name: env
  displayName: Environment
  type: string
  default: 'sbox'
  values:
  - sbox
  - test
  - staging
- name: databricksClusterId
  displayName: Databricks Cluster ID
  type: string
  default: '1121-123925-fa7rrd19'

name: ARIA Data Migration CI Pipeline - ${{ parameters.env }}
trigger:
- master

variables:
  resourceGroupName: ingest00-main-${{ parameters.env }}
  agentPool: "ubuntu-latest"

stages:
  - stage: Deploy to ${{ parameters.env }}
    displayName: Deploy Notebooks
    jobs:
    - template: pipeline/jobs/deploy.yaml
      parameters:
        agentPool: $(agentPool)
        pythonVersion: 3.10
        env: ${{ parameters.env }}
        mainRepositoryName: 'ARIAMigration-Databrick'
        databricksInstance: 'https://adb-3635282203417052.12.azuredatabricks.net'
        databricksClusterId: ${{ parameters.databricksClusterId }}