parameters:
- name: runTests
  type: boolean
  default: true
- name: env
  displayName: Environment
  type: string
  default: 'sbox'
  values:
  - sbox

name: ARIA Data Migration CI Pipeline - ${{ parameters.env }}
trigger:
- master

variables:
  resourceGroupName: ingest00-main-${{ parameters.env }}
  agentPool: "ubuntu-latest"
  ${{ if eq(parameters.env, 'prod') }}:
      runTests: false
  ${{ else }}:
      runTests: true

stages:
  - stage: Test_Permissions
    displayName: 'Test Agent Permissions'
    jobs:
    - template: pipeline/jobs/deploy.yaml
      parameters:
        agentPool: $(agentPool)
        pythonVersion: 3.10
        env: ${{ parameters.env }}