trigger: none

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Tests
    displayName: 'Pull Request: Run Unit Tests'
    jobs:
      - job: FunctionAppTests
        displayName: 'Run Function App Tests'
        steps:
          - template: ci_cd_templates/unit_tests/functionapp.yml

      - job: PaymentPendingTests
        displayName: 'Run Payment Pending Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/paymentPending.yml

      - job: ListingTests
        displayName: 'Run Listing Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/listing.yml

      - job: PrepareForHearingTests
        displayName: 'Run Prepare For Hearing Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/prepareForHearing.yml
