trigger: none

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Tests
    displayName: 'Pull Request: Run Unit Tests'
    jobs:
      - job: FunctionAppTests
        displayName: 'Run Function App Tests'
        steps:
          - template: ci_cd_templates/unit_tests/functionapp.yml

      - job: PaymentPendingTests
        displayName: 'Run Payment Pending Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/paymentPending.yml

      - job: AppealSubmittedTests
        displayName: 'Run Appeal Submitted Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/appealSubmitted.yml

      - job: AwaitingRespondentEvidenceATests
        displayName: 'Run Appeal Submitted Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/awaitingRespondentEvidenceA.yml

      - job: AwaitingRespondentEvidenceBTests
        displayName: 'Run Appeal Submitted Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/awaitingRespondentEvidenceB.yml

      - job: ListingTests
        displayName: 'Run Listing Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/listing.yml

      - job: PrepareForHearingTests
        displayName: 'Run Prepare For Hearing Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/prepareForHearing.yml

      - job: DecisionTests
        displayName: 'Run Decision Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/decision.yml

      - job: DecidedATests
        displayName: 'Run Decided_A Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/decided_a.yml

      - job: FTPASubmittedATests
        displayName: 'Run FTPASubmitted_A Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/ftpa_submitted_a.yml

      - job: FTPASubmittedBTests
        displayName: 'Run FTPASubmitted_B Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/ftpa_submitted_b.yml

      - job: FTPADecidedTests
        displayName: 'Run FTPA Decided Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/ftpa_decided.yml
          
      - job: EndedTests
        displayName: 'Run Ended Tests'
        steps:
          - template: ci_cd_templates/unit_tests/active/ended.yml
