stages:
  - stage: PR_Validation
    displayName: 'PR Validation - Linting'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: Linting
        displayName: 'Lint Tests'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
            inputs:
              versionSpec: '3.x'

          - script: |
              cd ${{ parameters.sourceDirectory }}/Databricks/ACTIVE/APPEALS/
              uv tool install ruff
              uv run ruff check ../Databricks ../AzureFunctions
            displayName: 'AzureFunction, Databricks code linting'