stages:
  - stage: PR_Validation
    displayName: 'PR Validation - Linting'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: Linting
        displayName: 'Lint Tests'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
            inputs:
              versionSpec: '3.x'

          - script: |
              cd ../Databricks/ACTIVE/APPEALS/
              pip install uv
              uv tool install ruff
              uv run ruff check $(Build.SourcesDirectory)/Databricks $(Build.SourcesDirectory)/AzureFunctions
              uv run ruff format --check $(Build.SourcesDirectory)/Databricks $(Build.SourcesDirectory)/AzureFunctions
            displayName: 'AzureFunction, Databricks code linting'