FtpaDecidedMandatoryTypes = {
    'addressLine1AdminJ': 'string',
    'addressLine2AdminJ': 'string',
    'addressLine3AdminJ': 'string',
    'addressLine4AdminJ': 'string',
    'adminDeclaration1': 'array<string>',
    'appealOutOfCountry': 'string',
    'appealReferenceNumber': 'string',
    'appealSubmissionDate': 'string',
    'appealSubmissionInternalDate': 'string',
    'appealType': 'string',
    'appealTypeDescription': 'string',
    'appellantAddress': 'struct<AddressLine1:string,AddressLine2:string,AddressLine3:string,PostTown:string,Country:string, County:string,PostCode:string>',
    'appellantDateOfBirth': 'string',
    'appellantFamilyName': 'string',
    'appellantGivenNames': 'string',
    'appellantHasFixedAddress': 'string',
    'appellantHasFixedAddressAdminJ': 'string',
    # 'appellantInDetention': 'string',
    'appellantInUk': 'string',
    'appellantLevelFlags': 'struct<details:array<struct<id:string,value:struct<dateTimeCreated:string,flagCode:string,hearingRelevant:string,name:string,path:array<struct<id:string,value:string>>,status:string>>>,partyName:string,roleOnCase:string>',
    'appellantNameForDisplay': 'string',
    'appellantNationalities': 'array<struct<id:string,value:struct<code:string>>>',
    'appellantNationalitiesDescription': 'string',
    'appellantPartyId': 'string',
    'appellantStateless': 'string',
    'appellantsRepresentation': 'string',
    'applicationChangeDesignatedHearingCentre': 'string',
    'applicationOutOfTimeExplanation': 'string',
    'ariaDesiredState': 'string',
    'ariaMigrationTaskDueDays': 'string',
    'autoHearingRequestEnabled': 'string',
    'caseFlags': 'struct<details:array<struct<id:string,value:struct<dateTimeCreated:string,flagCode:string,flagComment:string,hearingRelevant:string,name:string,path:array<struct<id:string,value:string>>,status:string>>>>',
    'caseLinks': 'array<string>',
    'caseManagementLocation': 'struct<baseLocation:string,region:string>',
    'caseManagementLocationRefData': 'struct<baseLocation:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>,region:string>',
    'caseNameHmctsInternal': 'string',
    'caseNotes': 'array<string>',
    'ccdReferenceNumberForDisplay': 'string',
    'changeDirectionDueDateActionAvailable': 'string',
    'countryGovUkOocAdminJ': 'string',
    #'dateEntryClearanceDecision': 'string',
    'decisionHearingFeeOption': 'string',
    'decisionLetterReceivedDate': 'string',
    'deportationOrderOptions': 'string',
    'displayMarkAsPaidEventForPartialRemission': 'string',
    'email': 'string',
    'feeAmountGbp': 'string',
    'feeDescription': 'string',
    'feePaymentAppealType': 'string',
    'feeVersion': 'string',
    'feeWithHearing': 'string',
    'feeWithoutHearing': 'string',
    'gwfReferenceNumber': 'string',
    'hasAddedLegalRepDetails': 'string',
    'hasOtherAppeals': 'string',
    'hasServiceRequestAlready': 'string',
    'hasSponsor': 'string',
    'haveHearingAttendeesAndDurationBeenRecorded': 'string',
    'hearingCentre': 'string',
    'hearingCentreDynamicList': 'struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>',
    'hmctsCaseCategory': 'string',
    'hmctsCaseNameInternal': 'string',
    'homeOfficeDecisionDate': 'string',
    'homeOfficeNotificationsEligible': 'string',
    'internalAppellantEmail': 'string',
    'isAdmin': 'string',
    'isAppellantMinor': 'string',
    'isAriaMigratedFeeExemption': 'string',
    'isCaseUsingLocationRefData': 'string',
    'isDlrmFeeRefundEnabled': 'string',
    'isDlrmFeeRemissionEnabled': 'string',
    'isEjp': 'string',
    'isFeePaymentEnabled': 'string',
    'isHomeOfficeIntegrationEnabled': 'string',
    'isIntegrated': 'string',
    'isNabaAdaEnabled': 'string',
    'isNabaEnabled': 'string',
    'isNabaEnabledOoc': 'string',
    'isOutOfCountryEnabled': 'string',
    'isRemissionsEnabled': 'string',
    'isServiceRequestTabVisibleConsideringRemissions': 'string',
    'legalRepresentativeDocuments': 'array<string>',
    'markAddendumEvidenceAsReviewedActionAvailable': 'string',
    'markEvidenceAsReviewedActionAvailable': 'string',
    'notificationsSent': 'array<string>',
    'oocAppealAdminJ': 'string',
    'paymentDescription': 'string',
    'paymentStatus': 'string',
    'remissionType': 'string',
    's94bStatus': 'string',
    'selectedHearingCentreRefData': 'string',
    'sendDirectionActionAvailable': 'string',
    'sponsorAddress': 'struct<AddressLine1:string,AddressLine2:string,AddressLine3:string,PostTown:string,County:string,Country:string,PostCode:string>',
    'staffLocation': 'string',
    'submissionOutOfTime': 'string',
    'submitNotificationStatus': 'string',
    'tribunalDocuments': 'array<string>',
    'tribunalReceivedDate': 'string',
    'uploadAddendumEvidenceActionAvailable': 'string',
    'uploadAddendumEvidenceAdminOfficerActionAvailable': 'string',
    'uploadAddendumEvidenceHomeOfficeActionAvailable': 'string',
    'uploadAddendumEvidenceLegalRepActionAvailable': 'string',
    'uploadAdditionalEvidenceActionAvailable': 'string',
    'uploadAdditionalEvidenceHomeOfficeActionAvailable': 'string',
    'uploadTheAppealFormDocs': 'array<string>',
    'paAppealTypePaymentOption': 'string',
    'rpDcAppealHearingOption': 'string',
    'paidAmount': 'string',
    'paidDate': 'string',
    'additionalPaymentInfo': 'string',
    'remissionDecision': 'string',
    'remissionDecisionReason': 'string',
    'amountRemitted': 'string',
    'amountLeftToPay': 'string',
    'appealWasNotSubmittedReason': 'string', #not mandatory
    'asylumSupportReference': 'string', #not mandatory
    'directions': 'array<string>',
    'feeRemissionType': 'string', #not mandatory
    'homeOfficeReferenceNumber': 'string', #not mandatory
    'legalAidAccountNumber': 'string', #not mandatory
    'legalRepAddressUK': 'struct<AddressLine1:string,AddressLine2:string,Country:string,County:string,PostCode:string,PostTown:string>', #not mandatory
    'legalRepCompanyPaperJ': 'string', #not mandatory
    'legalRepEmail': 'string', #not mandatory
    'legalRepFamilyNamePaperJ': 'string', #not mandatory
    'legalRepGivenName': 'string', #not mandatory
    'legalRepHasAddress': 'string', #not mandatory
    'legalRepIndividualPartyId': 'string', #not mandatory
    'legalRepOrganisationPartyId': 'string', #not mandatory
    'appellantFullName': 'string',
    'caseManagementCategory': 'struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>', #not mandatory
    'exceptionalCircumstances': 'string', #not mandatory
    'helpWithFeesReferenceNumber': 'string', #not mandatory
    'localAuthorityPolicy': 'struct<OrgPolicyCaseAssignedRole:string>', #not mandatory
    'recordedOutOfTimeDecision': 'string', #not mandatory
    'remissionClaim': 'string', #not mandatory
    'sponsorAuthorisation': 'string', #not mandatory 
    'sponsorEmailAdminJ': 'string', #not mandatory
    'sponsorFamilyName': 'string', #not mandatory
    'sponsorGivenNames': 'string', #not mandatory 
    'sponsorPartyId': 'string', #not mandatory
    'uploadHomeOfficeBundleAvailable': 'string', 
    'respondentDocuments': 'array<string>',
    'uploadHomeOfficeBundleActionAvailable': 'string',
    'additionalInstructionsTribunalResponse': 'string',
    'sponsorAddressForDisplay': 'string',
    'sponsorNameForDisplay': 'string',
    # 'appellantInterpreterSignLanguage': 'struct<languageManualEntry:array<string>,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>',
    'appellantInterpreterSpokenLanguage': 'struct<languageManualEntry:array<string>,languageManualEntryDescription:string,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>',
    'listingLength': 'struct<hours:bigint,minutes:bigint>',
    'appellantInterpreterSignLanguage': 'struct<languageManualEntry:array<string>,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>',
    'appellantInterpreterSpokenLanguage': 'struct<languageManualEntry:array<string>,languageManualEntryDescription:string,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>',
    'amendResponseActionAvailable': 'string',
    'appealResponseAvailable': 'string',
    'appealReviewOutcome': 'string',
    'appellantInterpreterLanguageCategory': 'array<string>',
    'currentHearingDetailsVisible': 'string',
    'datesToAvoidYesNo': 'string',
    'hearingChannel': 'struct<code:string,label:string>',
    'hearingDocuments': 'array<string>',
    'hearingRequirements': 'array<string>',
    'inCameraCourt': 'string',
    # 'inCameraCourtDecisionForDisplay': 'string', mandatory
    # 'inCameraCourtDescription': 'string', mandatory
    # 'inCameraCourtTribunalResponse': 'string', mandatory
    'isAdditionalAdjustmentsAllowed': 'string',
    'isAdditionalInstructionAllowed': 'string',
    'isAppealSuitableToFloat': 'string',
    'isAppellantAttendingTheHearing': 'string',
    'isAppellantGivingOralEvidence': 'string',
    'isEvidenceFromOutsideUkInCountry': 'string',
    'isEvidenceFromOutsideUkOoc': 'string',
    'isHearingLoopNeeded': 'string',
    'isHearingRoomNeeded': 'string',
    # 'isInCameraCourtAllowed': 'string', mandatory
    'isInterpreterServicesNeeded': 'string',
    'isMultimediaAllowed': 'string',
    'isRemoteHearing': 'string',
    'isRemoteHearingAllowed': 'string',
    # 'isSingleSexCourtAllowed': 'string', mandatory
    'isVulnerabilitiesAllowed': 'string',
    'isWitnessesAttending': 'string',
    'letterBundleDocuments': 'array<string>',
    'listingLocation': 'struct<code:string,label:string>',
    'multimediaDecisionForDisplay': 'string',
    'multimediaEvidence': 'string',
    'multimediaEvidenceDescription': 'string',
    'multimediaTribunalResponse': 'string',
    'otherDecisionForDisplay': 'string',
    'pastExperiences': 'string',
    'pastExperiencesDescription': 'string',
    'physicalOrMentalHealthIssues': 'string',
    'physicalOrMentalHealthIssuesDescription': 'string',
    'remoteHearingDecisionForDisplay': 'string',
    'remoteVideoCall': 'string',
    'remoteVideoCallDescription': 'string',
    'remoteVideoCallTribunalResponse': 'string',
    'reviewHomeOfficeResponseByLegalRep': 'string',
    'reviewResponseActionAvailable': 'string',
    'reviewedHearingRequirements': 'string',
    'singleSexCourt': 'string',
    # 'singleSexCourtDecisionForDisplay': 'string', mandatory
    # 'singleSexCourtTribunalResponse': 'string', mandatory
    # 'singleSexCourtType': 'string', mandatory
    # 'singleSexCourtTypeDescription': 'string', mandatory
    'submitHearingRequirementsAvailable': 'string',
    'uploadHomeOfficeAppealResponseActionAvailable': 'string',
    'uploadHomeOfficeBundleActionAvailable': 'string',
    'vulnerabilitiesDecisionForDisplay': 'string',
    'vulnerabilitiesTribunalResponse': 'string',
    'witnessDetails': 'array<string>',
    'bundleConfiguration': 'string',
    'bundleFileNamePrefix': 'string',
    'caseBundles': 'array<string>',
    'hmcts': 'string',
    'immigrationHistoryAgreement': 'string',
    'immigrationHistoryDisagreementDescription': 'string',
    'listCaseHearingCentre': 'string',
    'listCaseHearingCentreAddress': 'string',
    'listCaseHearingDate': 'string',
    'listCaseHearingLength': 'string',
    'oocAddressLine1': 'string',
    'scheduleOfIssuesAgreement': 'string',
    'scheduleOfIssuesDisagreementDescription': 'string',
    'stitchingStatus': 'string',
    'actualCaseHearingLength': 'struct<hours:string,minutes:string>',
    'anonymityOrder': 'string',
    'appealDate': 'string',
    'appealDecision': 'string',
    'appealDecisionAvailable': 'string',
    'attendingJudge': 'string',
    'finalDecisionAndReasonsDocuments': 'array<string>',
    'ftpaApplicationDeadline': 'string',
    'isDecisionAllowed': 'string',
    'oocAddressLine2': 'string',
    'oocAddressLine3': 'string',
    # 'oocAddressLine4': 'string',
    # 'oocLrCountryGovUkAdminJ': 'string',
    'sendDecisionsAndReasonsDate': 'string',
    'ftpaAppellantApplicationDate': 'string',
    'ftpaAppellantDocuments': 'array<string>',
    'ftpaAppellantEvidenceDocuments': 'array<string>',
    'ftpaAppellantGroundsDocuments': 'array<string>',
    'ftpaAppellantOutOfTimeDocuments': 'array<string>',
    'ftpaAppellantOutOfTimeExplanation': 'string',
    'ftpaAppellantSubmissionOutOfTime': 'string',
    'ftpaAppellantSubmitted': 'string',
    'ftpaRespondentApplicationDate': 'string',
    'ftpaRespondentDocuments': 'array<string>',
    'ftpaRespondentEvidenceDocuments': 'array<string>',
    'ftpaRespondentGroundsDocuments': 'array<string>',
    'ftpaRespondentOutOfTimeDocuments': 'array<string>',
    'ftpaRespondentOutOfTimeExplanation': 'string',
    'ftpaRespondentSubmissionOutOfTime': 'string',
    'ftpaRespondentSubmitted': 'string',
    'ftpaList': 'array<struct<id:string,value:struct<ftpaApplicant:string,ftpaApplicationDate:string,ftpaDecisionDate:string,ftpaDecisionOutcomeType:string,ftpaEvidenceDocuments:array<string>,ftpaGroundsDocuments:array<string>,ftpaOutOfTimeDocuments:array<string>,ftpaOutOfTimeExplanation:string,isFtpaNoticeOfDecisionSetAside:string>>>',
    'isFtpaAppellantDocsVisibleInDecided': 'string',
    'isFtpaAppellantDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantEvidenceDocsVisibleInDecided': 'string',
    'isFtpaAppellantEvidenceDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantGroundsDocsVisibleInDecided': 'string',
    'isFtpaAppellantGroundsDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantOotDocsVisibleInDecided': 'string',
    'isFtpaAppellantOotDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantOotExplanationVisibleInDecided': 'string',
    'isFtpaAppellantOotExplanationVisibleInSubmitted': 'string',
    'isFtpaListVisible': 'string',
    'isFtpaRespondentDocsVisibleInDecided': 'string',
    'isFtpaRespondentDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentEvidenceDocsVisibleInDecided': 'string',
    'isFtpaRespondentEvidenceDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentGroundsDocsVisibleInDecided': 'string',
    'isFtpaRespondentGroundsDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentOotDocsVisibleInDecided': 'string',
    'isFtpaRespondentOotDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentOotExplanationVisibleInDecided': 'string',
    'isFtpaRespondentOotExplanationVisibleInSubmitted': 'string',
    'judgeAllocationExists': 'string',
    'allocatedJudge': 'string',
    'allocatedJudgeEdit': 'string',
    'ftpaApplicantType': 'string',
    'ftpaFirstDecision': 'string',
    'ftpaAppellantDecisionDate': 'string',
    'ftpaRespondentDecisionDate': 'string',
    'ftpaFinalDecisionForDisplay': 'string',
    'ftpaAppellantRjDecisionOutcomeType': 'string',
    'ftpaRespondentRjDecisionOutcomeType': 'string',
    'isFtpaAppellantNoticeOfDecisionSetAside': 'string',
    'isFtpaRespondentNoticeOfDecisionSetAside': 'string',
    'isAppellantFtpaDecisionVisibleToAll': 'string',
    'isRespondentFtpaDecisionVisibleToAll': 'string',
    'isDlrmSetAsideEnabled': 'string',
    'isFtpaAppellantDecided': 'string',
    'isFtpaRespondentDecided': 'string',
    'isReheardAppealEnabled': 'string',
    'secondFtpaDecisionExists': 'string',
    'allFtpaAppellantDecisionDocs': 'array<string>',
    'allFtpaRespondentDecisionDocs': 'array<string>',
    'ftpaAppellantNoticeDocument': 'array<string>',
    'ftpaRespondentNoticeDocument': 'array<string>'
}


