ListingTypes = {
    'addressLine1AdminJ': 'string',
    'addressLine2AdminJ': 'string',
    'addressLine3AdminJ': 'string',
    'addressLine4AdminJ': 'string',
    'adminDeclaration1': 'array<string>',
    'appealOutOfCountry': 'string',
    'appealReferenceNumber': 'string',
    'appealSubmissionDate': 'string',
    'appealSubmissionInternalDate': 'string',
    'appealType': 'string',
    'appealTypeDescription': 'string',
    'appellantAddress': 'struct<AddressLine1:string,AddressLine2:string,AddressLine3:string,PostTown:string,Country:string,County:string,PostCode:string>',
    'appellantDateOfBirth': 'string',
    'appellantFamilyName': 'string',
    'appellantGivenNames': 'string',
    'appellantHasFixedAddress': 'string',
    'appellantHasFixedAddressAdminJ': 'string',
    # 'appellantInDetention': 'string',
    'appellantInUk': 'string',
    'appellantLevelFlags': 'struct<details:array<struct<id:string,value:struct<dateTimeCreated:string,flagCode:string,hearingRelevant:string,name:string,path:array<struct<id:string,value:string>>,status:string>>>,partyName:string,roleOnCase:string>',
    'appellantNameForDisplay': 'string',
    'appellantNationalities': 'array<struct<id:string,value:struct<code:string>>>',
    'appellantNationalitiesDescription': 'string',
    'appellantPartyId': 'string',
    'appellantStateless': 'string',
    'appellantsRepresentation': 'string',
    'applicationChangeDesignatedHearingCentre': 'string',
    'applicationOutOfTimeExplanation': 'string',
    'ariaDesiredState': 'string',
    'ariaMigrationTaskDueDays': 'string',
    'autoHearingRequestEnabled': 'string',
    'caseFlags': 'struct<details:array<struct<id:string,value:struct<dateTimeCreated:string,flagCode:string,flagComment:string,hearingRelevant:string,name:string,path:array<struct<id:string,value:string>>,status:string>>>>',
    'caseLinks': 'array<string>',
    'caseManagementLocation': 'struct<baseLocation:string,region:string>',
    'caseManagementLocationRefData': 'struct<baseLocation:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>,region:string>',
    'caseNameHmctsInternal': 'string',
    'caseNotes': 'array<string>',
    'ccdReferenceNumberForDisplay': 'string',
    'changeDirectionDueDateActionAvailable': 'string',
    'countryGovUkOocAdminJ': 'string',
    #'dateEntryClearanceDecision': 'string',
    'decisionHearingFeeOption': 'string',
    'decisionLetterReceivedDate': 'string',
    'deportationOrderOptions': 'string',
    'displayMarkAsPaidEventForPartialRemission': 'string',
    'email': 'string',
    'feeAmountGbp': 'string',
    'feeDescription': 'string',
    'feePaymentAppealType': 'string',
    'feeVersion': 'string',
    'feeWithHearing': 'string',
    'feeWithoutHearing': 'string',
    'gwfReferenceNumber': 'string',
    'hasAddedLegalRepDetails': 'string',
    'hasOtherAppeals': 'string',
    'hasServiceRequestAlready': 'string',
    'hasSponsor': 'string',
    'haveHearingAttendeesAndDurationBeenRecorded': 'string',
    'hearingCentre': 'string',
    'hearingCentreDynamicList': 'struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>',
    'hmctsCaseCategory': 'string',
    'hmctsCaseNameInternal': 'string',
    'homeOfficeDecisionDate': 'string',
    'homeOfficeNotificationsEligible': 'string',
    'internalAppellantEmail': 'string',
    'isAdmin': 'string',
    'isAppellantMinor': 'string',
    'isAriaMigratedFeeExemption': 'string',
    'isCaseUsingLocationRefData': 'string',
    'isDlrmFeeRefundEnabled': 'string',
    'isDlrmFeeRemissionEnabled': 'string',
    'isEjp': 'string',
    'isFeePaymentEnabled': 'string',
    'isHomeOfficeIntegrationEnabled': 'string',
    'isIntegrated': 'string',
    'isNabaAdaEnabled': 'string',
    'isNabaEnabled': 'string',
    'isNabaEnabledOoc': 'string',
    'isOutOfCountryEnabled': 'string',
    'isRemissionsEnabled': 'string',
    'isServiceRequestTabVisibleConsideringRemissions': 'string',
    'legalRepresentativeDocuments': 'array<string>',
    'markAddendumEvidenceAsReviewedActionAvailable': 'string',
    'markEvidenceAsReviewedActionAvailable': 'string',
    'notificationsSent': 'array<string>',
    'oocAppealAdminJ': 'string',
    'paymentDescription': 'string',
    'paymentStatus': 'string',
    'remissionType': 'string',
    's94bStatus': 'string',
    'selectedHearingCentreRefData': 'string',
    'sendDirectionActionAvailable': 'string',
    'sponsorAddress': 'struct<AddressLine1:string,AddressLine2:string,AddressLine3:string,PostTown:string,County:string,Country:string,PostCode:string>',
    'staffLocation': 'string',
    'submissionOutOfTime': 'string',
    'submitNotificationStatus': 'string',
    'tribunalDocuments': 'array<string>',
    'tribunalReceivedDate': 'string',
    'uploadAddendumEvidenceActionAvailable': 'string',
    'uploadAddendumEvidenceAdminOfficerActionAvailable': 'string',
    'uploadAddendumEvidenceHomeOfficeActionAvailable': 'string',
    'uploadAddendumEvidenceLegalRepActionAvailable': 'string',
    'uploadAdditionalEvidenceActionAvailable': 'string',
    'uploadAdditionalEvidenceHomeOfficeActionAvailable': 'string',
    'uploadTheAppealFormDocs': 'array<string>',
    'rpDcAppealHearingOption': 'string',
    'paidAmount': 'string',
    'paidDate': 'string',
    'additionalPaymentInfo': 'string',
    'remissionDecision': 'string',
    'remissionDecisionReason': 'string',
    'amountRemitted': 'string',
    'amountLeftToPay': 'string',
    'asylumSupportReference': 'string', #not mandatory
    'directions': 'array<string>',
    'feeRemissionType': 'string', #not mandatory
    'homeOfficeReferenceNumber': 'string', #not mandatory
    'legalAidAccountNumber': 'string', #not mandatory
    'legalRepIndividualPartyId': 'string', #not mandatory
    'legalRepOrganisationPartyId': 'string', #not mandatory
    'appellantFullName': 'string',
    'exceptionalCircumstances': 'string', #not mandatory
    'helpWithFeesReferenceNumber': 'string', #not mandatory
    'recordedOutOfTimeDecision': 'string', #not mandatory
    'remissionClaim': 'string', #not mandatory
    'sponsorAuthorisation': 'string', #not mandatory 
    'sponsorEmailAdminJ': 'string', #not mandatory
    'sponsorFamilyName': 'string', #not mandatory
    'sponsorGivenNames': 'string', #not mandatory 
    'sponsorPartyId': 'string', #not mandatory
    'uploadHomeOfficeBundleAvailable': 'string', 
    'respondentDocuments': 'array<string>',
    'uploadHomeOfficeBundleActionAvailable': 'string',
    'additionalInstructionsTribunalResponse': 'string',
    'sponsorAddressForDisplay': 'string',
    'sponsorNameForDisplay': 'string',
    'uploadHomeOfficeBundleActionAvailable': 'string',
    'isAppellantAttendingTheHearing': 'string',
    'isAppellantGivingOralEvidence': 'string',
    'isWitnessesAttending': 'string',
    'isHearingRoomNeeded': 'string',
    'isHearingLoopNeeded': 'string',
    'isInterpreterServicesNeeded': 'string',
    'appellantInterpreterLanguageCategory': 'array<string>',
    'appellantInterpreterSpokenLanguage': 'struct<languageManualEntry:array<string>,languageManualEntryDescription:string,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>',
    'remoteVideoCall': 'string',
    'remoteVideoCallDescription': 'string',
    'physicalOrMentalHealthIssues': 'string',
    'physicalOrMentalHealthIssuesDescription': 'string',
    'pastExperiences': 'string',
    'pastExperiencesDescription': 'string',
    'multimediaEvidence': 'string',
    'multimediaEvidenceDescription': 'string',
    'additionalRequests': 'string',
    'additionalRequestsDescription': 'string',
    'isEvidenceFromOutsideUkOoc': 'string',
    'isEvidenceFromOutsideUkInCountry': 'string',
    'oocAddressLine1': 'string',
    'oocAddressLine2': 'string',
    'oocAddressLine3': 'string',
    'oocLrCountryGovUkAdminJ': 'string',
    'amendResponseActionAvailable': 'string',
    'currentHearingDetailsVisible': 'string',
    'reviewResponseActionAvailable': 'string',
    'reviewHomeOfficeResponseByLegalRep': 'string',
    'submitHearingRequirementsAvailable': 'string',
    'reviewedHearingRequirements': 'string',
    'uploadHomeOfficeAppealResponseActionAvailable': 'string',
    'uploadHomeOfficeBundleActionAvailable': 'string',
    'appealReviewOutcome': 'string',
    'hearingRequirements': 'array<string>',
    'inCameraCourt': 'string',
    'inCameraCourtDescription': 'string',
    'singleSexCourt': 'string',
    'singleSexCourtType': 'string',
    'singleSexCourtTypeDescription': 'string',
    'datesToAvoidYesNo': 'string'


}