stages:
  - stage: paymentPending_unitTests
    displayName: 'PaymentPending Unit Tests'
    condition: eq(variables['Build.Reason'], 'PullRequest')

    jobs:
    - job: RunTests
      displayName: Run Python Unit Tests
      steps:
        - task: UsePythonVersion@0
          displayName: 'Use Python 3.x'
          inputs:
            versionSpec: '3.x'

        - script: |
            pip install uv
            uv pip install -r $(Build.SourcesDirectory)/tests/active/requirements.txt --system
          displayName: 'Install dependencies'
        
        - script: |
            echo "Running paymentPending unit tests for ${{ deployment.environment }}"
            pytest $(Build.SourcesDirectory)/tests/active/paymentPending \
              --junitxml=$(Build.ArtifactStagingDirectory)/pytest-results-${{ deployment.environment }}.xml -v
          displayName: 'Run pytest unit tests'
        
        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '$(Build.ArtifactStagingDirectory)/pytest-results-*.xml'
            testRunTitle: 'PaymentPending Unit Tests'
            mergeTestResults: true
            failTaskOnFailedTests: true
