RemittedNonMandatoryTypes = {
    'dateEntryClearanceDecision': 'string',
    'rpDcAppealHearingOption': 'string',
    'asylumSupportReference': 'string',
    'feeRemissionType': 'string',
    'legalAidAccountNumber': 'string',
    'legalRepAddressUK': 'struct<AddressLine1:string,AddressLine2:string,Country:string,County:string,PostCode:string,PostTown:string>',
    'helpWithFeesReferenceNumber': 'string',
    'remissionClaim': 'string',
    'appellantInterpreterSignLanguage': 'struct<languageManualEntry:array<string>,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>',
    'inCameraCourtDecisionForDisplay': 'string',
    'inCameraCourtDescription': 'string',
    'inCameraCourtTribunalResponse': 'string',
    'isInCameraCourtAllowed': 'string',
    'isSingleSexCourtAllowed': 'string',
    'singleSexCourtDecisionForDisplay': 'string',
    'singleSexCourtTribunalResponse': 'string',
    'singleSexCourtType': 'string',
    'singleSexCourtTypeDescription': 'string',
    'oocAddressLine1': 'string',
    'oocAddressLine2': 'string',
    'oocAddressLine3': 'string',
    'oocAddressLine4': 'string',
    'oocLrCountryGovUkAdminJ': 'string',
    'judgeAllocationExists': 'string',
    'allocatedJudge': 'string',
    'allocatedJudgeEdit': 'string',
    'judgesNamesToExclude': 'string',
    'ftpaAppellantSubmitted': 'string',
    'isFtpaAppellantDocsVisibleInDecided': 'string',
    'isFtpaAppellantDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantOotDocsVisibleInDecided': 'string',
    'isFtpaAppellantOotDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantGroundsDocsVisibleInDecided': 'string',
    'isFtpaAppellantEvidenceDocsVisibleInDecided': 'string',
    'isFtpaAppellantGroundsDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantEvidenceDocsVisibleInSubmitted': 'string',
    'isFtpaAppellantOotExplanationVisibleInDecided': 'string',
    'isFtpaAppellantOotExplanationVisibleInSubmitted': 'string',
    'ftpaRespondentSubmitted': 'string',
    'isFtpaRespondentDocsVisibleInDecided': 'string',
    'isFtpaRespondentDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentOotDocsVisibleInDecided': 'string',
    'isFtpaRespondentOotDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentGroundsDocsVisibleInDecided': 'string',
    'isFtpaRespondentEvidenceDocsVisibleInDecided': 'string',
    'isFtpaRespondentGroundsDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentEvidenceDocsVisibleInSubmitted': 'string',
    'isFtpaRespondentOotExplanationVisibleInDecided': 'string',
    'isFtpaRespondentOotExplanationVisibleInSubmitted': 'string',
    'ftpaApplicantType': 'string',
    # 'ftpaFirstDecision': 'string',
    # 'ftpaDecisionDate': 'string',
    'ftpaFinalDecisionForDisplay': 'string',
    'ftpaAppellantDecisionDate': 'string',
    'ftpaRespondentDecisionDate': 'string',
    'ftpaAppellantApplicationDate': 'string',
    'ftpaRespondentApplicationDate': 'string',
    'ftpaAppellantSubmissionOutOfTime': 'string',
    'ftpaRespondentSubmissionOutOfTime': 'string',
    'ftpaAppellantOutOfTimeExplanation': 'string',
    'ftpaRespondentOutOfTimeExplanation': 'string',
    'isFtpaAppellantNoticeOfDecisionSetAside': 'string',
    'isFtpaRespondentNoticeOfDecisionSetAside': 'string',
    'isAppellantFtpaDecisionVisibleToAll': 'string',
    'isRespondentFtpaDecisionVisibleToAll': 'string',
    'ftpaAppellantNoticeDocument': 'array<string>',
    'ftpaRespondentNoticeDocument': 'array<string>',
    'ftpaAppellantRjDecisionOutcomeType': 'string',
    'ftpaRespondentRjDecisionOutcomeType': 'string',
    'isFtpaAppellantDecided': 'string',
    'isFtpaRespondentDecided': 'string',
    'ftpaList': 'array<struct<id:string,value:struct<ftpaApplicant:string,ftpaApplicationDate:string,ftpaDecisionDate:string,ftpaDecisionOutcomeType:string,ftpaEvidenceDocuments:array<string>,ftpaGroundsDocuments:array<string>,ftpaOutOfTimeDocuments:array<string>,ftpaOutOfTimeExplanation:string,isFtpaNoticeOfDecisionSetAside:string>>>',
    'allFtpaAppellantDecisionDocs': 'array<string>',
    'allFtpaRespondentDecisionDocs': 'array<string>',
    'allSetAsideDocs': 'array<string>',
    'reasonRehearingRule32': 'string',
    'rule32ListingAdditionalIns': 'string',
    'updateTribunalDecisionDateRule32': 'string',
    'updateTribunalDecisionList': 'string',
    'ftpaAppellantDecisionRemadeRule32Text': 'string',
    'ftpaRespondentDecisionRemadeRule32Text': 'string',
    'ftpaFinalDecisionRemadeRule32': 'string',
    # 'isDlrmSetAsideEnabled': 'string',
    'isReheardAppealEnabled': 'string',
    # 'caseFlagSetAsideReheardExists': 'string',
    'secondFtpaDecisionExists': 'string',
    'isFtpaNoticeOfDecisionSetAside': 'string',
    'ftpaRespondentDocuments': 'array<string>',
    'ftpaRespondentEvidenceDocuments': 'array<string>',
    'ftpaRespondentGroundsDocuments': 'array<string>',
    'ftpaRespondentOutOfTimeDocuments': 'array<string>',
    'isDlrmSetAsideEnabled': 'string',
    'endAppealOutcome': 'string', # field not in remitted
    'endAppealOutcomeReason': 'string', # field not in remitted
    'endAppealApproverType': 'string', # field not in remitted
    'endAppealApproverName': 'string', # field not in remitted
    'endAppealDate': 'string', # field not in remitted
    'stateBeforeEndAppeal': 'string', # field not in remitted
    'decisionLetterReceivedDate': 'string',
    'appellantInterpreterSpokenLanguage': 'struct<languageManualEntry:array<string>,languageManualEntryDescription:string,languageRefData:struct<list_items:array<struct<code:string,label:string>>,value:struct<code:string,label:string>>>'


}